### ISSUE TITLE
ocaml-expect fails with odd error message

### ISSUE THREAD

**Issue by yminsky** [janestreet/toplevel_expect_test#1]
/Users/yminsky/.opam/system/bin/ocaml-expect be executed inside the mercurial repository it was built for!

Any ideas what's going on?

**Comment by yminsky** [comment]
I guess it's just this line:

https://github.com/janestreet/toplevel_expect_test/blob/master/src/main.ml#L297

which was designed for internal Jane Street use, I imagine, and we'll have to generalize for external use.

**Comment by ghost** [comment]
Ah, I removed most of these specific bits, but my test environment was inside our mercurial repo, that's why I didn't catch that...

**Comment by ghost** [comment]
Fixed in 113.33.02

**Comment by Drup** [comment]
I stumbled on this. However, I can't upgrade since 113.33.0{2,3} have the constraint `"ocaml" {= "4.02.3"}` in opam (but not 01). Is the constraint bogus ?

**Comment by ghost** [comment]
It's well possible that the constraint is bogus, there is a new v0.9.0 coming release coming soon, once https://github.com/ocaml/opam-repository/pull/8792 is ready
