### ISSUE TITLE
syntax errors don't work

### ISSUE THREAD

**Issue by yminsky** [janestreet/toplevel_expect_test#3]
When I try something with a syntax error, the whole script fails, rather than reporting the syntax error.  In particular, this file:

```
let x-y = 3
[%%expect]
```

fails as follows:

```
$ ocaml-expect w.ml
File "w.ml", line 1, characters 6-7:
Error: Syntax error
```

**Comment by ghost** [comment]
That's a known limitation. `[%%expect]` nodes are part of the syntax, so supporting this would require a parser that support syntax errors. Maybe using the merlin parser would work...

**Comment by yminsky** [comment]
Got it.  This seems like a minor issue, and probably not worth fixing right now.  Closing.
