### ISSUE TITLE
ocaml-expect calls `patdiff`

### ISSUE THREAD

**Issue by Drup** [janestreet/toplevel_expect_test#5]
I have no idea where `patdiff` comes from. `diff` is fine too, you should test for availability and use the one actually available.

**Comment by hhugo** [comment]
https://github.com/janestreet/patdiff

**Comment by Drup** [comment]
Oh, so ocaml-expect even requires `core_extended`, through `patdiff`.

Please use `diff`...

**Comment by ghost** [comment]
You can use `-diff-command diff`

**Comment by hhugo** [comment]
It should now automatically fallback to `diff` if patdiff is not available
